---
title: "Examining extraneous variables by group"
author: Lindsay Rutter
output:
  packagedocs::package_docs:
  toc: true
toc_collapse: true
vignette: >
  %\VignetteEngine{packagedocs::redirect}
---
  
  <meta http-equiv="content-type" content="text/html;charset=utf-8" />
  
  ```{r global_options, include=FALSE}
# R output pre blocks are styled by default to indicate output
knitr::opts_chunk$set(
  comment = NA,
  cache = TRUE,
  fig.height = 8,
  fig.width = 10
)
```

```{r}
library(edgeR)
library(ggplot2)
library(GGally)
library(EDASeq)
library(utils)
library(dplyr)

rm(list=ls())
thisPath <- "/Users/lindz/bigPint"
beeCounts <- read.delim(file=paste0(thisPath, "/AllLaneCount.txt"), row.names=1, stringsAsFactors = FALSE)
colnames(beeCounts) <- c("NC.1", "NC.2", "NR.1", "VR.1", "NS.1", "VP.1", "NS.2", "VR.2", "NP.1", "VP.2", "VC.1", "NP.2", "VP.3", "NP.3", "VS.1", "VS.2", "VC.2", "NC.3", "VP.4", "NC.4", "NR.2", "VC.3", "VC.4", "NP.4", "VR.3", "NC.5", "VS.3", "NP.5", "VC.5", "VS.4", "NS.3", "VS.5", "VP.5", "NR.3", "NR.4", "VC.6", "NS.4", "NC.6", "NP.6", "VR.4", "NR.5", "NR.6", "NS.5", "VP.6", "NS.6", "VR.5", "VR.6", "VS.6")
beeCounts <- beeCounts[ , order(names(beeCounts))]
# beeCounts <- beeCounts[ , order(c(paste0(rep("NP",6),".",1:6), paste0(rep("NC",6),".",1:6), paste0(rep("NR",6),".",1:6), paste0(rep("NS",6),".",1:6), paste0(rep("VP",6),".",1:6), paste0(rep("VC",6),".",1:6), paste0(rep("VR",6),".",1:6), paste0(rep("VS",6),".",1:6)))]

x <- DGEList(counts=beeCounts)

exVars <- read.csv("/Users/lindz/bigPint/tblshoot/CheckAllVars/extraVarClean.csv")

x$samples$group <- as.factor(unlist(lapply(colnames(x), function(x) substring(unlist(strsplit(x, "[.]"))[1],1))))
x$samples$virus <- as.factor(unlist(lapply(colnames(x), function(x) substring(unlist(strsplit(x, "[.]"))[1],1,1))))
x$samples$diet <- as.factor(unlist(lapply(colnames(x), function(x) substring(unlist(strsplit(x, "[.]"))[1],2,2))))
x$samples$lane <- exVars$Lane
x$samples$day <- exVars$Day
x$samples$mortality <- exVars$Mortality
x$samples$sbv <- exVars$SBV
x$samples$iapv <- exVars$IAPV
x$samples$rnaConc <- exVars$rnaConc
x$samples$rin <- exVars$RIN
```

```{r}
x$samples$group <- factor(x$samples$group, levels = c("NP", "NC", "NR", "NS", "VP", "VC", "VR", "VS"), ordered = TRUE)

ggplot(x$samples, aes(x=group, y=mortality)) + geom_boxplot(aes(fill=group)) + geom_point()
```

```{r}
ggplot(x$samples, aes(x=group, y=sbv)) + geom_boxplot(aes(fill=group)) + geom_point()
```

```{r}
ggplot(x$samples, aes(x=group, y=iapv)) + geom_boxplot(aes(fill=group)) + geom_point()
```

```{r}
ggplot(x$samples, aes(x=group, y=rnaConc)) + geom_boxplot(aes(fill=group)) + geom_point()
```

```{r}
ggplot(x$samples, aes(x=group, y=rin)) + geom_boxplot(aes(fill=group)) + geom_point()
```
